### PR TITLE
Make GetQrText method public

### PR DESCRIPTION
**Pull request by omeaart**
While trying to use this library in our ecosystem I need the raw data of the qrcode instead of an image. This change allows me to do this without manual building the data string.

### CODE REVIEW

**Comment by RobThree** [comment]
Hmmm, it should've been public to begin with, as it is [in the PHP implementation](https://github.com/RobThree/TwoFactorAuth/blob/3407c33775391fa8c36f7d766f26c5e59a736374/lib/TwoFactorAuth.php#L175). Thanks! 👍

**Comment by alansingfield** [comment]
Hello,

This isn't in the official Nuget release yet, is this something you can do please?

Thanks.

**Comment by RobThree** [comment]
[It is now](https://www.nuget.org/packages/TwoFactorAuth.Net/1.3.9) 😉

**Comment by alansingfield** [comment]
Thank you. I can now take the URL and add &image=url to the end of it, so I get my application's icon appearing in the FreeOTP app. Not sure which other systems might support this but it works for me...

https://stackoverflow.com/questions/41232168/token-image-in-google-authenticator-or-freeotp

**Pull request merged**
